name: iOS Build

on:
    workflow_dispatch

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build web assets
      run: npm run build

    - name: Install Capacitor CLI
      run: npm install -g @capacitor/cli

    - name: Sync Capacitor
      run: npx cap sync ios

    - name: Install CocoaPods dependencies
      run: |
        cd ios/App
        pod install

    - name: Build iOS app
      run: xcodebuild -workspace ios/App/App.xcworkspace -scheme App -sdk iphoneos -configuration Release archive -archivePath ${{ github.workspace }}/App.xcarchive

    - name: Export IPA
      run: |
        xcodebuild -exportArchive -archivePath ${{ github.workspace }}/App.xcarchive -exportOptionsPlist ios/App/ExportOptions.plist -exportPath ${{ github.workspace }}/output

    - name: Upload IPA as artifact
      uses: actions/upload-artifact@v3
      with:
        name: iOS-App
        path: ${{ github.workspace }}/output/*.ipa